### PR TITLE
Update _footer.html

### PR DESCRIPTION
**Pull request by giuliazanchi**
Updated footer to include CC-BY-SA license information.

### CODE REVIEW

**Comment by petesfrench** [comment]
LGTM, just wondering, do we need to include the version of the licence?

**Comment by giuliazanchi** [comment]
Hi @petesfrench , I'm not sure, other TAs who have implemented this change have used this text, as preapproved by Legal. I'll check and let you know tomorrow.

**Comment by giuliazanchi** [comment]
Hi again @petesfrench , here's the answer:

> The[ licensing page](https://sites.google.com/a/canonical.com/operations/legal/software-licensing#h.w171o4ftougj) does specify version 3.0 so we can make it  "CC-BY-SA 3.0"

I'll fix this in my PR and wait for your OK or further comments. Thanks!

**Review by petesfrench — APPROVED** [review]
LGTM

**Pull request merged**
