### PR TITLE
Update navigation with new logo/nav style

### PR DESCRIPTION
**Pull request by petesfrench**
## Done

- I have simply replaced the old [round logo](https://assets.ubuntu.com/v1/05caa6c5-Multipass-mark.svg) with the new [square logo](https://assets.ubuntu.com/v1/7b658b39-Favicon+-+Multipass.svg) as there were no details in the issue of exactly what to do

## Issue

FIxes: https://github.com/canonical/multipass.run/issues/271

### CODE REVIEW

**Comment by lyubomir-popov** [comment]
@petesfrench the new variable font has a slightly different weight distribution, allowing to use 400 as the main body text weight instead of 300 as was previously the case. To  make the nav look right, we need to use the 400 weight for the nav items, rather than the medium weight (which is now too bold). I've filed a vanilla issue to remedy this upstream, but if you could fix it locally, then this would unblock this pr. Can you please implement what I've requested in this [vanilla issue](https://github.com/canonical/vanilla-framework/issues/4634)?

**Comment by lyubomir-popov** [comment]
@petesfrench the nav items are now weight 300 not 400 
image

**Comment by petesfrench** [comment]
@lyubomir-popov It is my mistake, I should have read more carefully. I have updated them accordingly.

**Comment by lyubomir-popov** [comment]
Thanks @petesfrench +1

**Review by anthonydillon — APPROVED** [review]

**Pull request merged**
